---
# private vars:
## URL vars
_bundle_url_path_name: '/{{ bundle.name }}'
_bundle_url_skip_name: '{{ bundle.url_skip_name|default(True) }}'

_bundle_url_path_ver: '/{{ bundle.version }}'
_bundle_url_skip_ver: '{{ bundle.url_skip_ver|default(False) }}'

_bundle_url_path_binaries: '/binaries'
_bundle_url_skip_binaries: '{{ bundle.url_skip_binaries|default(True) }}'

_bundle_url_full: '{{ bundle.mirror }}{{ _bundle_url_skip_name|ternary("",_bundle_url_path_name) }}{{ _bundle_url_skip_ver|ternary("",_bundle_url_path_ver) }}{{ _bundle_url_skip_binaries|ternary("",_bundle_url_path_binaries) }}/{{ _bundle_archive }}'

## FILE vars
_bundle_sha_path_elem: '{{ (bundle.sha|default("")|length > 0)|ternary("-" + bundle.sha|default(""), "") }}'
_bundle_platform_path_elem: '{{ (bundle_platform|default("",True)|length > 0)|ternary("-" + bundle_platform|string, "") }}'
_bundle_suffix_path_elem: '{{ bundle.suffix|default("") }}'
_bundle_file_name: '{{ bundle.name }}-{{ bundle.version }}{{ _bundle_sha_path_elem }}{{ _bundle_platform_path_elem }}{{ _bundle_suffix_path_elem }}'

_bundle_archive: '{{ _bundle_file_name }}{{ bundle_archive_ext }}'
_bundle_unzip_strip_top: '{{ bundle.unzip_strip_top|default(True) }}'

## EXEC vars
_bundle_exec_path_default: 'bin/{{ software_name }}.sh'
_bundle_exec_path: '{{ bundle.exec_path|default(_bundle_exec_path_default) }}'

## INSTALL vars
_bundle_version_tag: '{{ (bundle.version[0]=="v")|ternary(bundle.version,"v" + bundle.version) }}'
_bundle_install_dir: '{{ bundle.install_dir|default(software_install_dir + "/" + software_name) }}'
_bundle_install_dir_ver: '{{ _bundle_install_dir }}/{{ _bundle_version_tag }}'
_bundle_install_dir_parent: '{{ _bundle_unzip_strip_top|ternary(_bundle_install_dir,_bundle_install_dir_ver)}}'
_bundle_install_dir_creates: '{{ _bundle_install_dir_parent }}/{{ bundle.name }}-{{ bundle.version }}'
_bundle_install_dir_bin: '{{ _bundle_install_dir_parent }}/bin'
_bundle_install_dir_default: '{{ _bundle_install_dir }}/default'