---
- name: 'Resolve platform specific vars'
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'
  tags: [oc, vars]

- when: oc_enabled
  block:
  - include_tasks: 'install.yml'
    tags: [oc, install]

  - include_tasks: 'plugins.yml'
    tags: [oc, plugins]

  - include_tasks: 'config.yml'
    tags: [oc, config]

  - name: Checking installed version of OC
    shell: oc version 2>&1 | head -n1 | awk '{print $2}'
    changed_when: False
    ignore_errors: yes
    register: oc_curr_version
    failed_when: oc_curr_version.stdout is version_compare(bundle.version + '+' + bundle.sha, '!=')
    tags: [oc, check]