---
- name: 'Set Oracle Java as default in system'
  alternatives:
    name: '{{ item.exe }}'
    link: '/usr/bin/{{ item.exe }}'
    path: '{{ item.path }}/{{ item.exe }}'
  become: yes
  with_items:
    - { path: '{{ joracle_home_path }}/jre/bin', exe: 'java' }
    - { path: '{{ joracle_home_path }}/jre/bin', exe: 'keytool' }
    - { path: '{{ joracle_home_path }}/bin', exe: 'javac' }
    - { path: '{{ joracle_home_path }}/bin', exe: 'javadoc' }
  when: joracle_set_default and joracle_task_rpm_install is changed
  register: joracle_task_set_default