---
- when: joracle_enabled
  block:
  - include_tasks: 'download.yml'
    tags: [joracle, download]

  - include_tasks: 'install.yml'
    tags: [joracle, install]

  - include_tasks: 'config.yml'
    tags: [joracle, config]

  - name: Checking installed version of JDK
    shell: java -version 2>&1 | head -n1 | cut -d'"' -f2
    changed_when: False
    ignore_errors: yes
    register: java_curr_version
    failed_when: java_curr_version.stdout is version_compare(joracle_version_string,'!=')
    tags: [joracle, check]