---
- include_tasks: deploy1.yml
  with_sequence:
    count={{ os7_masters_count }}
  vars:
    prefix: '{{ os7_master_name }}'
    flavor: '{{ os7_master_flavor }}'
    group: 'masters'
  no_log: '{{ False if debug else True }}'

- name: Wait for masters port 22 to be ready
  wait_for:
    port: 22
    host: '{{ hostvars[item].ansible_host }}'
    search_regex: OpenSSH
    delay: 10
  with_items: '{{ groups["masters"] }}'

- name: Add masters to inventory file
  lineinfile:
    dest: '{{ playbook_dir }}/hosts'
    regexp: '^{{ item }}'
    line: '{{item}} ansible_host={{ hostvars[item].ansible_host }} ip4_public={{ hostvars[item].ip4_public }} ip4_private={{ hostvars[item].ip4_private }}'
    insertafter: '\[masters\]'
    state: present
  changed_when: False
  with_items: '{{ groups["masters"] | reverse | list }}'

- include_tasks: deploy1.yml
  with_sequence:
    count={{ os7_slaves_count }}
  vars:
    prefix: '{{ os7_slave_name }}'
    flavor: '{{ os7_slave_flavor }}'
    group: 'slaves'
  no_log: '{{ False if debug else True }}'

- name: Wait for slaves port 22 to be ready
  wait_for:
    port: 22
    host: '{{ hostvars[item].ansible_host }}'
    search_regex: OpenSSH
    delay: 10
  with_items: '{{ groups["slaves"] }}'

- name: Add slaves to inventory file
  lineinfile:
    dest: '{{ playbook_dir }}/hosts'
    regexp: '^{{ item }}'
    line: '{{item}} ansible_host={{ hostvars[item].ansible_host }} ip4_public={{ hostvars[item].ip4_public }} ip4_private={{ hostvars[item].ip4_private }}'
    insertafter: '\[slaves\]'
    state: present
  changed_when: False
  with_items: '{{ groups["slaves"] | reverse | list }}'