---
- name: Deploy {{ prefix }}{{ item }} instance
  os_server:
#    cloud: '{{ os_cloud_name }}'
    name: '{{ prefix }}{{ item }}'
    image: '{{ os_image_name }}'
    flavor: '{{ flavor }}'
    key_name: '{{ os_key_name }}'
    network: '{{ os_net_name_priv }}'
    security_groups: '{{ os_security_group }}'
    auto_ip: false
    state: present
    timeout: 200
    verify: false
  register: os_nova_instance

- name: Assign floating IP to {{ prefix }}{{ item }}
  os_floating_ip:
#    cloud: '{{ os_cloud_name }}'
    server: '{{ os_nova_instance.id }}'
    reuse: yes
    state: present
    wait: yes
  register: 'os_instance_floating_ip'
  retries: 5
  until: os_instance_floating_ip is success

- name: Add {{ prefix }}{{ item }} instance to inventory
  add_host:
    name: '{{ os_nova_instance.server.name }}'
    groups: '{{ group }}'
    ansible_host: '{{ os_instance_floating_ip.floating_ip.floating_ip_address }}'