---
- name: Destroy master Instances
  os_server:
#    cloud: "{{ os7_cloud_name }}"
    name: "{{ os7_master_name }}{{ item }}"
    state: absent
  with_sequence:
    count={{ os7_masters_count }}

- name: Destroy slave Instances
  os_server:
#    cloud: "{{ os7_cloud_name }}"
    name: "{{ os7_slave_name }}{{ item }}"
    state: absent
  with_sequence:
    count={{ os7_slaves_count }}

#TODO Delete SSH key pair

#TODO Delete security group

#TODO Delete floating IPS

#TODO Delete router
#- os_router:
#    cloud: mycloud
#    state: absent
#    name: router1

#TODO Delete a subnet
#- os_subnet:
#    cloud: '{{ os7_cloud_name }}'
#    name: net1subnet
#    state: absent

#TODO Delete network
#  os_network:
#    cloud: '{{ os7_cloud_name }}'
#    name: '{{ os7_net_priv_name }}'
#    provider_network_type: vlan
#    state: absent