---
- name: 'Ensure PIP package installed'
  pip:
    name: 'shade'
    state: latest
    extra_args: -I
  become: yes
  no_log: '{{ False if debug else True }}'
  tags: [os7, pip]

- when: os7_enabled
  block:
  - include_tasks: network.yml
    tags: [os7, network]
#TODO take image from Images or download new one
#  - include_tasks: image.yml
  - include_tasks: secgroup.yml
    tags: [os7, security]
  - include_tasks: sshkey.yml
    tags: [os7, sshkey]
  - include_tasks: deploy.yml
    tags: [os7, deploy]
  - include_tasks: destroy.yml
    tags: [os7, never, destroy]
  # block
