---
- name: Create private {{ os7_net_priv_name }} network
  os_network:
    name: '{{ os7_net_priv_name }}'
#    provider_network_type: vlan
    external: false
    shared: false
    state: present
    verify: '{{ os7_validate_ssl_certs }}'
  register: os7_network_priv
  tags: [os7, network]

- name: Create private {{ os7_subnet_priv_name }} subnet
  os_subnet:
    network_name: "{{ os7_network_priv.id }}"
    name: '{{ os7_subnet_priv_name }}'
    ip_version: 4
    cidr: 192.168.1.0/24
    gateway_ip: 192.168.1.1
    enable_dhcp: yes
    state: present
    verify: '{{ os7_validate_ssl_certs }}'
  register: os7_subnet_priv
  tags: [os7, network]

- name: Create router for {{ os7_net_priv_name }} network
  os_router:
    name: '{{ os7_router_priv_name }}'
    network: '{{ os7_net_pub_name }}'
    interfaces:
      - '{{ os7_subnet_priv_name }}'
    state: present
    verify: '{{ os7_validate_ssl_certs }}'
  tags: [os7, network]