---
- name: Create private {{ os7_net_priv_name }} network
  os_network:
#    cloud: '{{ os7_cloud_name }}'
    name: '{{ os7_net_priv_name }}'
#    provider_network_type: vlan
    external: false
    shared: false
    verify: false
    state: present
  register: os7_network_priv

- name: Create private {{ os7_subnet_priv_name }} subnet
  os_subnet:
#    cloud: '{{ os7_cloud_name }}'
    network_name: "{{ os7_network_priv.id }}"
    name: '{{ os7_subnet_priv_name }}'
    ip_version: 4
    cidr: 192.168.1.0/24
    gateway_ip: 192.168.1.1
    enable_dhcp: yes
    verify: false
    state: present
    dns_nameservers:
      - 8.8.8.8
      - 8.8.4.4
  register: os7_subnet_priv

#TODO network ID should be added to vars
- name: Create router for {{ os7_net_priv_name }} network
  os_router:
#    cloud: '{{ os7_cloud_name }}'
    name: '{{ os7_router_priv_name }}'
    network: 'c29a0c92-6721-4e83-b9b4-d1a2c7d11495'
    interfaces:
      - '{{ os7_subnet_priv_name }}'
    verify: false
    state: present