---
- name: Create {{ os7_security_group_name }} security group
  os_security_group:
#    cloud: '{{ os7_cloud_name }}'
    name: '{{ os7_security_group_name }}'
    description: '{{ os7_security_group_desc }}'
    verify: false
    state: present
  tags: [os7, security]

- name: Create rules for {{ os7_security_group_name }} security group
  os_security_group_rule:
#    cloud: '{{ os7_cloud_name }}'
    security_group: '{{ os7_security_group_name }}'
    protocol: '{{ item.value.proto }}'
    port_range_min: '{{ item.value.port_range_min }}'
    port_range_max: '{{ item.value.port_range_max }}'
    remote_ip_prefix: '{{ item.value.remote_ip_prefix }}'
    verify: '{{ os7_validate_ssl_certs }}'
  with_dict: '{{ os7_security_rules }}'
  tags: [os7, security]