---
- name: Upload SSH {{ os7_sshkey_name }} keypair
  os_keypair:
    name:  '{{ os7_sshkey_name }}'
    public_key_file: '{{ local_whoami_home }}/.ssh/ec2.centos.pub'
    state: present
    verify: '{{ os7_validate_ssl_certs }}'
  tags: [os7, sshkey]