---
- name: Create && Launch VMs
  hosts: localhost
  gather_facts: yes
  vars:
    tools_owner_name: '{{ lookup("env","USER") }}'
    tools_owner_home: '{{ lookup("env","HOME") }}'
    whoami_home: '{{ tools_owner_home }}'
  roles:
    - cloud/os7
  tasks:
    - include_role: name=tools/gatling
    - include_role: name=tools/jmeter
    - include_role: name=tools/locust
    - include_role: name=tools/maven
    - include_role: name=tools/oc

- name: Install Performance Tooling
  hosts: masters:slaves
  gather_facts: yes
  vars:
    tools_owner_name: 'jenkins'
    tools_owner_home: '/var/lib/jenkins'
    whoami_home: '{{ lookup("env","HOME") }}'
  roles:
    - system/docker
    - system/ohmyzsh
    - tools/gatling
    - tools/jmeter
    - tools/locust
    - tools/maven
    - tools/oc
    - zabbix

- name: Add VMs to Jenkins master
  hosts: localhost
  gather_facts: no
  vars:
    whoami_home: '{{ lookup("env","HOME") }}'
  vars_files:
    - secret.yml
  roles:
    - pjenkins