---
- name: Create && Launch VMs
  hosts: localhost
  gather_facts: yes
  vars:
    current_username: '{{ lookup("env","USER") }}'
    current_userhome: '{{ lookup("env","HOME") }}'
  roles:
    - os7spin
  tasks:
    - include_role: name=gatling
    - include_role: name=jmeter
    - include_role: name=octools

- name: Install Performance Tooling
  hosts: masters:slaves
  gather_facts: yes
  vars:
    current_username: 'jenkins'
  roles:
    - system
    - joracle
    - jenkins
    - ohmyzsh
    - maven
    - locust
    - zabbix
    - docker
    - octools
    - gatling
    - jmeter

#- name: Add EC2 instances to Jenkins master
#  hosts: localhost
#  gather_facts: false
#  environment:
#    PYTHONHTTPSVERIFY: 0
#  vars_files:
#    - secret.yml
#  roles:
#    - pjenkins