---
- name: Create && Launch VMs
  hosts: localhost
  gather_facts: yes
  vars:
    whoami_home: '{{ lookup("env","HOME") }}'
  roles:
    - os7spin
  tasks:
    - include_role: name=gatling
    - include_role: name=jmeter
    - include_role: name=octools

- name: Install Performance Tooling
  hosts: masters:slaves
  gather_facts: yes
  vars:
    tools_owner_name: 'jenkins'
    tools_owner_home: '/var/lib/jenkins'
    whoami_home: '{{ lookup("env","HOME") }}'
  roles:
    - system
    - joracle
    - jenkins
    - ohmyzsh
    - maven
    - locust
    - zabbix
    - docker
    - octools
    - gatling
    - jmeter

- name: Add VMs to Jenkins master
  hosts: localhost
  gather_facts: no
  vars:
    whoami_home: '{{ lookup("env","HOME") }}'
  vars_files:
    - secret.yml
  roles:
    - pjenkins