---
- name: Create && Launch VMs
  hosts: localhost
  gather_facts: True
  vars:
    tools_owner_name: '{{ lookup("env","USER") }}'
    tools_owner_home: '{{ lookup("env","HOME") }}'
    local_whoami_home: '{{ tools_owner_home }}'
  roles:
    - cloud/os7
  tasks:
    - include_role: name=tools/locust
    - include_role: name=tools/maven
    - include_role: name=tools/oc

- name: Install Performance Tooling
  hosts: masters:slaves
  gather_facts: '{{ hostvars["localhost"]["cloud_destroyed"]|default(False)|ternary(False, True) }}'
  vars:
    tools_owner_name: 'jenkins'
    tools_owner_home: '/var/lib/jenkins'
    local_whoami_home: '{{ lookup("env","HOME") }}'
    ansible_pkg_mgr: 'yum'
  pre_tasks:
    - meta: end_play
      when: hostvars["localhost"]["cloud_destroyed"]|default(False)
  roles:
    - system/docker
    - system/ohmyzsh
    - tools/locust
    - tools/maven
    - tools/oc
    - zabbix
  post_tasks:
    - copy:
        src: '{{ local_whoami_home }}/.ssh/ec2.jenkins'
        dest: '{{ tools_owner_home }}/.ssh/id_rsa'
        mode: 0600
        remote_src: no
      become: yes
      become_user: '{{ tools_owner_name }}'
      when: inventory_hostname_short in groups["masters"]

- name: Add VMs to Jenkins master
  hosts: localhost
  gather_facts: no
  vars:
    local_whoami_home: '{{ lookup("env","HOME") }}'
  vars_files:
    - secret.yml
  roles:
    - pjenkins