---
- name: 'Create SSH credentials'
  jenkins_cli:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    kwargs:
      credentialsId: '{{ jenkins.ssh.credentials.id }}'
      userName: '{{ jenkins.user.name }}'
      description: '{{ jenkins.ssh.credentials.description }}'
      userPrivateKey: '{{ jenkins.ssh.credentials.package }}.BasicSSHUserPrivateKey'
      privateKeySource: '{{ jenkins.ssh.credentials.package }}.BasicSSHUserPrivateKey.DirectEntryPrivateKeySource'
      sshKeyText: '{{ item }}'
      sshKeyPassphrase: '{{ jenkins.ssh.key.passphrase }}'
  with_file: '{{ whoami_home }}/.ssh/ec2.jenkins'
  register: result
  no_log: '{{ False if debug else True }}'

- name: 'Check existing Master nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: node_exists
    args: '{{ host }}'
  with_items: '{{ groups["masters"] }}'
  loop_control:
    loop_var: host
  register: jenkins_existed_masters
  no_log: '{{ False if debug else True }}'

- debug: var=jenkins_existed_masters
  when: debug

- name: 'Check existing Slave nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: node_exists
    args: '{{ host }}'
  with_items: '{{ groups["slaves"] }}'
  loop_control:
    loop_var: host
  register: jenkins_existed_slaves
  no_log: '{{ False if debug else True }}'

- debug: var=jenkins_existed_slaves
  when: debug

- name: 'Delete existing Master nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: delete_node
    args: '{{ master.host }}'
  when: master.node_exists
  with_items: '{{ jenkins_existed_masters.results }}'
  loop_control:
    loop_var: master
  no_log: '{{ False if debug else True }}'

- name: 'Delete existing Slave nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: delete_node
    args: '{{ slave.host }}'
  when: slave.node_exists
  with_items: '{{ jenkins_existed_slaves.results }}'
  loop_control:
    loop_var: slave
  no_log: '{{ False if debug else True }}'

- name: 'Create new Master nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: create_node
    args: '{{ host }}'
    kwargs:
      numExecutors: '{{ jenkins.slave.executors }}'
      nodeDescription: '{{ jenkins.slave.description }}'
      remoteFS: '{{ jenkins.user.home }}'
      labels: '{{ jenkins.slave.labels|join(" ") }} master'
      launcher: '{{ jenkins.slave.launcher }}'
      launcher_params:
        port: '{{ jenkins.slave.port }}'
        username: '{{ jenkins.user.name }}'
        credentialsId: '{{ jenkins.ssh.credentials.id }}'
        host: '{{ hostvars[host].ansible_host }}'
  with_items: '{{ groups["masters"] }}'
  loop_control:
    loop_var: host
  no_log: '{{ False if debug else True }}'

- name: 'Create new Slave nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: create_node
    args: '{{ host }}'
    kwargs:
      numExecutors: '{{ jenkins.slave.executors }}'
      nodeDescription: '{{ jenkins.slave.description }}'
      remoteFS: '{{ jenkins.user.home }}'
      labels: '{{ jenkins.slave.labels|join(" ") }} slave'
      launcher: '{{ jenkins.slave.launcher }}'
      launcher_params:
        port: '{{ jenkins.slave.port }}'
        username: '{{ jenkins.user.name }}'
        credentialsId: '{{ jenkins.ssh.credentials.id }}'
        host: '{{ hostvars[host].ansible_host }}'
  with_items: '{{ groups["slaves"] }}'
  loop_control:
    loop_var: host
  no_log: '{{ False if debug else True }}'