---
- name: 'Create SSH credentials'
  jenkins_cli:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    kwargs:
      groovyScript: '{{role_path}}/library/scripts/create_credentials.xgroovy'
      credentialsId: '{{ jenkins.ssh.credentials.id }}'
      userName: '{{ jenkins.user.name }}'
      description: '{{ jenkins.ssh.credentials.description }}'
      userPrivateKey: '{{ jenkins.ssh.credentials.package }}.BasicSSHUserPrivateKey'
      privateKeySource: '{{ jenkins.ssh.credentials.package }}.BasicSSHUserPrivateKey.DirectEntryPrivateKeySource'
      sshKeyText: '{{ item }}'
      sshKeyPassphrase: '{{ jenkins.ssh.key.passphrase }}'
  with_file: '{{ local_whoami_home }}/.ssh/ec2.jenkins'
  register: result
  no_log: '{{ False if debug else True }}'
  tags: [pjenkins, create, sshkey]

- name: 'Create new Master nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: create_node
    args: '{{ host }}'
    kwargs:
      numExecutors: '{{ jenkins.slave.executors }}'
      nodeDescription: '{{ jenkins.slave.description }}'
      remoteFS: '{{ jenkins.user.home }}'
      labels: '{{ jenkins.slave.labels|join(" ") }} master'
      launcher: '{{ jenkins.slave.launcher }}'
      launcher_params:
        port: '{{ jenkins.slave.port }}'
        username: '{{ jenkins.user.name }}'
        credentialsId: '{{ jenkins.ssh.credentials.id }}'
        host: '{{ hostvars[host].ansible_host }}'
  with_items: '{{ groups["masters"] }}'
  loop_control:
    loop_var: host
  no_log: '{{ False if debug else True }}'
  tags: [pjenkins, create, masters]

- name: 'Create new Slave nodes'
  jenkins_api:
    jenkins_url: '{{ jenkins.master.url }}'
    username: '{{ jenkins.admin.username }}'
    password: '{{ jenkins.admin.password }}'
    command: create_node
    args: '{{ host }}'
    kwargs:
      numExecutors: '{{ jenkins.slave.executors }}'
      nodeDescription: '{{ jenkins.slave.description }}'
      remoteFS: '{{ jenkins.user.home }}'
      labels: '{{ jenkins.slave.labels|join(" ") }} slave'
      launcher: '{{ jenkins.slave.launcher }}'
      launcher_params:
        port: '{{ jenkins.slave.port }}'
        username: '{{ jenkins.user.name }}'
        credentialsId: '{{ jenkins.ssh.credentials.id }}'
        host: '{{ hostvars[host].ansible_host }}'
  with_items: '{{ groups["slaves"] }}'
  loop_control:
    loop_var: host
  no_log: '{{ False if debug else True }}'
  tags: [pjenkins, create, slaves]