#TODO BUG https://bugs.launchpad.net/python-jenkins/+bug/1769425
#only ver0.4.16 can be used for now!!!
- name: 'Install python-jenkins'
  pip:
    name: python-jenkins
    version: 0.4.16
    state: present
  become: yes
  tags: [pjenkins, install]

- include_tasks: config.yml
  tags: [pjenkins, config]