---
- name: 'Ensure ZSH package installed'
  action: '{{ ansible_pkg_mgr }}'
  args:
    name: 'zsh'
    state: present
  become: yes
  tags: [ohmyzsh, install]

- name: Clone oh-my-zsh repo
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
  become_user: '{{ current_username }}'
  become: yes
  tags: [ohmyzsh, install]

- name: Create a new zsh config
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    remote_src: yes
  become_user: '{{ current_username }}'
  become: yes
  tags: [ohmyzsh, config]

- name: Set zsh as default shell
  user:
    name: '{{ current_username }}'
    shell: /usr/bin/zsh
  become: yes
  tags: [ohmyzsh, config]