---
- name: 'Ensure ZSH package installed'
  action: '{{ ansible_pkg_mgr }}'
  args:
    name: 'zsh'
    state: present
  become: yes
  register: zsh_pkg_installed
  tags: [ohmyzsh, packages]

#TODO backup old ~/.zshrc if needed
#- name: Backing up existing ~/.zshrc
#  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi
#  when: zsh_pkg_installed is success
#  sudo: no

- name: Clone oh-my-zsh repo
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: '{{ tools_owner_home }}/.oh-my-zsh'
  become_user: '{{ tools_owner_name }}'
  become: yes
  when: zsh_pkg_installed is success
  register: ohmyzsh_repo_cloned
  tags: [ohmyzsh, clone]

- name: Create a new zsh config
  copy:
    src: '{{ tools_owner_home }}/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '{{ tools_owner_home }}/.zshrc'
    remote_src: yes
  become_user: '{{ tools_owner_name }}'
  become: yes
  when: ohmyzsh_repo_cloned is success
  register: ohmyzsh_config_created
  tags: [ohmyzsh, config]

- name: Set zsh as default shell
  user:
    name: '{{ tools_owner_name }}'
    shell: /usr/bin/zsh
  become: yes
  when: ohmyzsh_config_created is success
  tags: [ohmyzsh, config]