---
- name: Deploy master Instances
  os_server:
#    cloud: '{{ os_cloud_name }}'
    name: '{{ os_master_prefix }}{{ item }}'
    image: '{{ os_image_name }}'
    flavor: '{{ os_master_flavor }}'
    key_name: '{{ os_key_name }}'
    network: '{{ os_net_name_priv }}'
    security_groups: '{{ os_security_group }}'
    verify: false
    state: present
    timeout: 200
  register: os_nova_masters
  with_sequence:
    count={{ os_masters_count }}
  no_log: True

- name: Add masters to Inventory
  add_host:
    name: "{{ item.server.name }}"
    groups: masters
    ansible_ssh_host: '{{ item.server.accessIPv4 }}'
  with_items: '{{ os_nova_masters.results }}'
  no_log: True

- name: Deploy slave Instances
  os_server:
#    cloud: '{{ os_cloud_name }}'
    name: '{{ os_slave_prefix }}{{ item }}'
    image: '{{ os_image_name }}'
    flavor: '{{ os_slave_flavor }}'
    key_name: '{{ os_key_name }}'
    network: '{{ os_net_name_priv }}'
    security_groups: '{{ os_security_group }}'
    verify: false
    state: present
    timeout: 200
  register: os_nova_slaves
  with_sequence:
    count={{ os_slaves_count }}
  no_log: True

- name: Add slaves to Inventory
  add_host:
    name: "{{ item.server.name }}"
    groups: slaves
    ansible_ssh_host: '{{ item.server.accessIPv4 }}'
  with_items: '{{ os_nova_slaves.results }}'
  no_log: True

- name: Wait for port 22 to be ready
  wait_for:
    port: 22
    host: '{{ hostvars[item].ansible_ssh_host }}'
    search_regex: OpenSSH
    delay: 10
  with_items:
    - '{{ groups.masters }}'
    - '{{ groups.slaves }}'