- name: 'Resolve platform specific vars'
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'
  tags: [maven, vars]

- when: maven_enabled
  block:
  - include_tasks: 'install.yml'
    tags: [maven, install]

  - include_tasks: 'plugins.yml'
    tags: [maven, plugins]

  - include_tasks: 'config.yml'
    tags: [maven, config]

  - name: Checking installed version of maven
    shell: mvn -v 2>&1 | head -n1 | awk '{print $3}'
    changed_when: False
    ignore_errors: yes
    register: maven_curr_version
    failed_when: maven_curr_version.stdout is version_compare(bundle.version,'!=')
    tags: [maven, check]