---
- name: Install latest Oracle JDK RPM
  action: "{{ ansible_pkg_mgr }} name={{ joracle_dir_source }}/{{ oracle_java_rpm_filename }} state=present"
  become: yes
  when: not oracle_java_task_rpm_download|skipped
  register: oracle_java_task_rpm_install
  tags: [joracle, install]
