---
- name: 'Install latest Oracle JDK RPM'
  action: "{{ ansible_pkg_mgr }} name={{ joracle_dir_source }}/{{ joracle_rpm_filename }} state=present"
  become: yes
  when: not joracle_task_rpm_download|skipped
  register: joracle_task_rpm_install
