---
- name: Ensure all RPM packages updated
  yum: 
    name: '*'
    state: latest
  become: yes
  tags: [system, packages]

- name: Ensure RPM packages installed
  yum:
    pkg: '{{ item }}'
    state: latest
  become: yes
  tags: [system, packages]
  with_items:
    - curl
    - epel-release
    - git
    - mc
    - ntp
    - net-tools
    - tree
    - unzip
    - vim
    - wget
    - zip

- name: Ensure the NTP service is running and enabled
  service:
    name: ntpd
    state: started
    enabled: True
  become: yes
  tags: [system, ntp]

- name: Ensure MOTD file is present and updated
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  become: yes
  tags: [system, motd]

- name: Set System limits
  lineinfile: dest=/etc/security/limits.conf line='{{ item.key }}' regexp='{{ item.value }}'
  with_dict:
    "*               soft    nofile          65536" : '\*\s+soft\s+nofile'
    "*               hard    nofile          65536" : '\*\s+hard\s+nofile'
    "root            soft    nofile          16384" : 'root\s+soft\s+nofile'
    "root            hard    nofile          65536" : 'root\s+hard\s+nofile'
  become: yes
  changed_when: False
  tags: [system, limits]

- name: Set LC_ALL and LANG parameters
  lineinfile:
    dest: /etc/environment
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^LANG=', line: 'LANG=en_US.utf-8' }
    - { regexp: '^LC_ALL=', line: 'LC_ALL=en_US.utf-8' }

#- name: Create /etc/hosts file
#  template:
#    src: hosts.j2
#    dest: /etc/hosts
#    owner: root
#    group: root
#    mode: 0644
#  become: yes
#  tags: [system, hosts]

#- name: Ensure hostname is the same of the inventory
#  hostname:
#    name: '{{ inventory_hostname }}'
#  become: yes
#  tags: [system, hostname]

#- name: Make Centos user sudoer
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    line: '{{ jenkins.user.name }}	ALL=(ALL:ALL) NOPASSWD:ALL'
#    validate: 'visudo -cf %s'
#  become: yes
#  changed_when: False
#  tags: [jenkins, user]