---
- name: 'Add insecure registry to sysconfig'
  lineinfile:
    path: /etc/sysconfig/docker
    create: yes
    state: present
    line: '{{ docker_sysconfig_options }}'
  changed_when: False
  become: yes
  tags: [docker, config]

- name: Creates directory
  file:
    path: /etc/docker
    state: directory
  become: yes
  tags: [docker, config]

- name: 'Adding insecure registry to daemon'
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644
  become: yes
  tags: [docker, config]