---
- name: 'Create Jenkins user'
  user:
    name: '{{ jenkins.user.name }}'
    home: '{{ jenkins.user.home }}'
    shell: /bin/bash
    state: present
  become: yes
  tags: [jenkins, user]

- name: 'Add master public key to authorized keys'
  authorized_key:
    user: '{{ jenkins.user.name }}'
    key: '{{ item }}'
    state: present
  become: yes
  with_file: '{{ local_whoami_home }}/.ssh/ec2.jenkins.pub'
  no_log: '{{ False if debug else True }}'
  tags: [jenkins, user]

- name: 'Update authorized_keys rights'
  file: 
    path: '{{ jenkins.user.home }}/.ssh/authorized_keys'
    state: file
    mode: 0600
  become: yes
  become_user: '{{ jenkins.user.name }}'
  tags: [jenkins, user]

#TODO Check if jenkins super need root access
#- name: Make Jenkins user sudoer
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    line: '{{ jenkins.user.name }}	ALL=(ALL:ALL) NOPASSWD:ALL'
#    validate: 'visudo -cf %s'
#  become: yes
#  changed_when: False