---
- name: 'Insert/Update JMeter properties using a template file'
  lineinfile:
    path: '{{ jmeter_installation_default_bin }}/{{ filename }}.properties'
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
  when: filename|default(None) != None
  with_items: '{{ jmeter_config_props[filename] }}'