---
- name: 'Resolve platform specific vars'
  include_vars: '{{item}}'
  with_first_found:
    - files:
        - '{{ansible_distribution}}-{{ansible_distribution_release}}.yml'
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      skip: true
      paths:
        - '{{role_path}}/vars'
  tags: [jmeter, vars]

- when: jmeter_enabled
  block:
  - include_tasks: 'install.yml'
    tags: [jmeter, install]

  - include_tasks: 'plugins.yml'
    tags: [jmeter, plugins]

  - include_tasks: 'config.yml'
    tags: [jmeter, config]