---
- include_tasks: user.yml
  tags: [jenkins, user]

- name: 'Ensure correct java version selected'
  alternatives:
    name: java
    path: /usr/java/latest/jre/bin/java
  become: yes
  tags: [jenkins, config]

- name: 'Set nproc limits for Jenkins'
  lineinfile:
    dest: /etc/security/limits.conf
    line: '{{ item.key }}'
    regexp: '{{ item.value }}'
  with_dict:
    'jenkins      hard    nproc      unlimited' : 'jenkins\s+hard\s+nproc'
    'jenkins      soft    nproc      unlimited' : 'jenkins\s+soft\s+nproc'
  become: yes
  changed_when: False
  tags: [jenkins, limits]