---
- include: user.yml

- name: Ensure correct java version selected
  alternatives:
    name: java
    path: /usr/java/latest/jre/bin/java
  tags: [jenkins, config]

- name: Set nproc limits for Jenkins
  lineinfile: dest="/etc/security/limits.d/20-nproc.conf" line='jenkins    soft    nproc     unlimited'
  become: yes
  changed_when: false
  tags: [jenkins, config]