---
- name: 'Ensure Jenkins user'
  user:
    name: '{{ jenkins.user.name }}'
    home: '{{ jenkins.user.home }}'
    shell: /bin/bash
    state: present

- name: 'Add master public key to authorized keys'
  authorized_key:
    user: '{{ jenkins.user.name }}'
    key: '{{ item }}'
  with_file: ~/.ssh/ec2.jenkins.pub

- name: 'Update authorized_keys rights'
  file: 
    path: '{{ jenkins.user.home }}/.ssh/authorized_keys'
    state: file
    mode: 0600 
    owner: jenkins