---
- name: Ensure Jenkins user
  user:
    name: '{{ jenkins_user_name }}'
    home: '{{ jenkins_user_home }}'
    shell: /bin/bash
    state: present
  become: yes
  tags: [jenkins, user]  

- name: Make Jenkins user sudoer
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ jenkins_user_name }}	ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  become: yes
  changed_when: false  
  tags: [jenkins, user]

- name: Add master public key to authorized keys
  authorized_key:
    user: '{{ jenkins_user_name }}'
    key: '{{ item }}'
  with_file: ~/.ssh/ec2.jenkins.pub
  become: yes
  
  tags: [jenkins, user]

- name: Update authorized_keys rights
  file: 
    path: '{{ jenkins_user_home }}/.ssh/authorized_keys'
    state: file
    mode: 0600 
    owner: jenkins
  become: yes
  tags: [jenkins, user]