os7_enabled: yes
#TODO add sshkey also to host_facts
host_facts:
  user_name: centos
  connection_port: 22
  connection_type: ssh

os7_prefix: '{{ cloud_vm_prefix|default("mperf-") }}'
os7_cloud_name: mwqa
os7_masters_count: 2
os7_master_flavor: m1.large
os7_slaves_count: 5
os7_slave_flavor: m1.medium

os7_image_id: 'd1b458f6-245d-4b62-9035-07629fbd7081'
os7_master_name: '{{ os7_prefix }}master'
os7_slave_name: '{{ os7_prefix }}slave'
os7_sshkey_name: '{{ os7_prefix }}sshkey'
#os7_net_priv_name: '{{ os7_prefix }}net1-private'
os7_net_priv_name: 'mobile-jenkins'
os7_subnet_priv_name: '{{ os7_prefix }}subnet1-private'
os7_router_priv_name: '{{ os7_prefix }}router1'

os7_security_group_name: '{{ os7_prefix }}sec-group1'
os7_security_group_desc: 'Security group for performance testing instances'

os7_security_rules:
  icmp:
    name: '{{ os7_prefix }}icmp'
    description: Allow ICMP access
    proto: icmp
    port_range_min: -1
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0
  ssh:
    name: '{{ os7_prefix }}ssh'
    description: Allow SSH access
    proto: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  jmeter:
    name: '{{ os7_prefix }}jmeter'
    description: Allow JMeter access
    proto: tcp
    port_range_min: 1099
    port_range_max: 1099
    remote_ip_prefix: 0.0.0.0/0
  psql:
    name: '{{ os7_prefix }}psql'
    description: Allow PSQL access
    proto: tcp
    port_range_min: 5432
    port_range_max: 5433
    remote_ip_prefix: 0.0.0.0/0
  http:
    name: '{{ os7_prefix }}web-def'
    description: Allow HTTP access
    proto: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  https:
    name: '{{ os7_prefix }}web-ssl'
    description: Allow HTTPs access
    proto: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  jboss:
    name: '{{ os7_prefix }}web-dev'
    description: Allow JBoss access
    proto: tcp
    port_range_min: 8080
    port_range_max: 8089
    remote_ip_prefix: 0.0.0.0/0
  locust:
    name: '{{ os7_prefix }}locust'
    description: Allow locust.io access
    proto: tcp
    port_range_min: 5557
    port_range_max: 5558
    remote_ip_prefix: 0.0.0.0/0