---
- name: 'Add DockerCE repository'
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    baseurl: '{{ item.baseurl }}'
    gpgkey: '{{ item.gpgkey }}'
    gpgcheck: '{{ item.gpgcheck }}'
    enabled: '{{ item.enabled }}'
  become: yes
  with_items: '{{ docker_yum_repos }}'

- name: 'Install DockerCE dependencies'
  action: '{{ ansible_pkg_mgr }}'
  args:
    name: '{{ item }}'
    state: latest
  become: yes
  with_items: '{{ docker_required_packages }}'
  no_log: False if debug else True

- name: 'Install docker-ce version'
  action: '{{ ansible_pkg_mgr }}'
  args:
    name: 'docker-ce'
    state: latest
  become: yes

- name: 'Add {{ user_name.stdout }} to docker group'
  user:
    name: '{{ user_name.stdout }}'
    groups:
      - docker
    append: yes
  become: yes
  register: docker_group_add
#  notify:
#    - 'Kill SSH sessions'