---
- name: Configure EC2 security groups
  ec2_group:
    name: '{{ item.name }}'
    description: '{{ item.description}}'
    region: '{{ ec2_region }}'
    rules:
      - proto: '{{ item.proto }}'
        from_port: '{{ item.port }}'
        to_port: '{{ item.port }}'
        cidr_ip: 0.0.0.0/0
  with_items:
    - {name: mperf-jmeter, description: Allow Remote Method Invocation (RMI) access, proto: tcp, port: 1099}
    - {name: mperf-ssh, description: Allow SSH access, proto: tcp, port: 22}
  tags: [ec2, sec-group]


- name: Configure Outbound security group
  ec2_group:
    name: mperf-outbound
    description: Allow outbound connections to the internet
    region: "{{ ec2_region }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  tags: [ec2, sec-group]
