---
- name: Get the Centos EBS SSD AMI
  ec2_ami_find:
    architecture: x86_64
    name: 'CentOS Linux 7*EBS*'
    region: '{{ ec2_region }}'
    sort: creationDate
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: centos_ami_find
  tags: [ec2, find-vmi]

- name: Start the instances
  ec2:
    region: '{{ ec2_region }}'
    image: '{{ centos_ami_find.results[0].ami_id }}'
    instance_type: '{{ ec2_instance_type }}'
    key_name: '{{ ec2_key_name }}'
    group: [jmeter, ssh, outbound]
    instance_tags: {Name: mperf1, type: performance, env: testing}
    exact_count: '{{ ec2_instance_count }}'
    count_tag: {type: performance}
    wait: yes
  register: ec2
  tags: [ec2, start-vms]

- name: Add instances to group
  add_host:
    hostname: '{{ item.public_dns_name }}'
    groups: performance
  with_items: '{{ ec2.tagged_instances }}'
  when: item.public_dns_name is defined
  tags: [ec2, group-vms]

- name: Wait for SSH server to be running
  wait_for:
    host: '{{ item.public_dns_name }}'
    port: 22
    search_regex: OpenSSH
  with_items: '{{ ec2.tagged_instances }}'
  when: item.public_dns_name is defined
  tags: [ec2, wait-vms]